FROM golang:1.11-stretch AS BUILD
RUN mkdir /app
ADD . /app/
WORKDIR /app
RUN CGO_ENABLED=0 GOOS=linux GOARCH=arm GOARM=7 go build -a -installsuffix cgo -o ingestd .

FROM armhf/alpine
RUN apk update && apk add ca-certificates && rm -rf /var/cache/apk/*
RUN mkdir /app
ENV SERVER_PORT=9000
COPY --from=BUILD /app/ingestd .
CMD ["./ingestd"]
EXPOSE 9000